language: python
python:
  - 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

install:
  # Install this package and the packages listed in requirements.txt.
  - pip install .
  # Install extra requirements for running tests and building docs.
  - pip install -r requirements-dev.txt

script:
  - coverage run -m pytest  # Run the tests and check for test coverage.
  - coverage report -m  # Generate test coverage report.
  - codecov  # Upload the report to codecov.
  #- flake8  # Enforce code style ('relaxed' line length limit is set in .flake8 config file).
  - make -C docs html  # Build the documentation.

env:
  global:
    # Doctr deploy key for vstadnytskyi/laue-crystallography
    - secure: "yFl/HfprmpkLThZ1eZQJtCY2iTZiMd9R310FB7kYdZ6/bPpsyKOnjL8PWpWDf6fJi0YQnTzX4lN3TXTJfd1bHUqttuY23oIs3TAeBvTwuayFA8M0LvGtHVHzir1TG
    FeB7cMxboDzZeFy8SrNwt8nxituVp4toOKPsSpPgVbrvnhg9APemBTlkOJWAO2xYbj02QR9Oofpm768GNbok9HeCXCPjbdOE3+8f2GjGPZSz/WUZgF/a9wSaAFJPRb3qLgIcUnwIc/YumLTN
    GxQSKTpQkJftlbucNOul1wG3ecbjqjAnKFGOLv4iajsSDuyo3M4J6GVQ2klt2duWtTbzCAvk6oQp3FlHBFa3bqTTXjfcjAwjuVgdRiWReDmNCr5vG+CJOphXq0O0wQeIQvcPDi3LEIQjDumC
    C0+bq7tOyCnUIIBCyfvwzewhi9BkF8z+goHxizMvqW4scblloYUWsmGp2k1KHvPASEYHZtu66Ibj0O+jGXvZmi036yijQkK7ycij0jz8d3jeNfllkfxJEv6QJdd2o2dcYEI4yMPgcacrvlrF
    HFVVx+FP9rKfF/oRONsMhDsXkzTv+LDcSpEMZ6TRO00HzDD7EN35k4NSNBRA3vOCyGQzvzRFohbuHoAa7GL8V7HzgqISuzuWhksJV6LqTcTCXHRiwvjQeQ962BfdOI="
